// Mocks generated by Mockito 5.4.0 from annotations
// in interview_task_app/test/features/posts/presentation/viewModel/post_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:interview_task_app/features/posts/data/post_data_source.dart'
    as _i2;
import 'package:interview_task_app/features/posts/repository/entities/post.dart'
    as _i5;
import 'package:interview_task_app/features/posts/repository/post_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostDataSource_0 extends _i1.SmartFake
    implements _i2.PostDataSource {
  _FakePostDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostDataSource get postDataProvider => (super.noSuchMethod(
        Invocation.getter(#postDataProvider),
        returnValue: _FakePostDataSource_0(
          this,
          Invocation.getter(#postDataProvider),
        ),
      ) as _i2.PostDataSource);
  @override
  _i4.Future<List<_i5.Post>> getPosts(int? pageNumber) => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [pageNumber],
        ),
        returnValue: _i4.Future<List<_i5.Post>>.value(<_i5.Post>[]),
      ) as _i4.Future<List<_i5.Post>>);
}
